version: '3.4'

services:
  gateway-account:
    image: l2/gateway-account:0.1.0
    container_name: gateway-account
    ports:
      - 5041:80
    depends_on:
      - api-account
  api-account:
    image: l2/api-account:0.1.0
    container_name: api-account
    extra_hosts:
      dockerhost: 172.17.0.1
    environment:
      ConnectionString: Host=dockerhost;Port=5432;Database=l2_account;Username=postgres;Password=1qazxsw2
      DockerHost: dockerhost
      JWTSettingSecretKey: l2_server_end_api_account
      JWTSettingIssuer: zen
      JWTSettingAudience: api_account
      JWTSettingAccessExpiration: 60
      JWTSettingRefreshExpiration: 80
